*** Variables ***
${BROWSER}    chrome
${WEB_URL}    https://panaryco.wixsite.com/myhotel?utm_source=chatgpt.com

${NAME}         John
${LNAME}        Doe
${TELPHONE}     087-876-9861
${EMAIL}        john@mail.scb

${XPATH_FNAME}    //*[@id='input_comp-lt33fcq41']
${XPATH_LNAME}    //*[@id='input_comp-lt33fcs1']
${XPATH_TEL}      //*[@id='input_comp-lt33fcsi1']
${XPATH_MAIL}     //*[@id='input_comp-lt33fcsf1']
${XPATH_ACCEPT_TERMS}     //*[@id="comp-ltubl84u"]/input
${XPATH_ADULTS_NO}    //*[@id="collection_comp-lt33fcsl1"]